# NumPy Practice

This notebook gives you hands-on practice with the core NumPy skills from `01_Introduction_to_Numpy.ipynb`. You will create arrays in several ways, inspect their properties, reshape and index into them, and apply arithmetic operations, both element-wise and along a specific axis. Work through the challenges in order, as later ones build on earlier results.

---

## Starter Code

In [16]:
# Import NumPy, run this cell first
import numpy as np

## Part 1: Creating Arrays

### Challenge 1: Array from a list

Create a NumPy array from the following Python list:

```python
my_list = [1, 2, 5, 6, 8]
```

Print the array and its `dtype`.

In [17]:
# Array from a list
my_list = [1, 2, 5, 6, 8]
arr_list = np.array(my_list)
print(arr_list)
print(arr_list.dtype)

[1 2 5 6 8]
int64


### Challenge 2: Range array

Create a NumPy array containing the integers from **1 to 10** (inclusive).

In [18]:
# Integers 1 to 10, the stop value is exclusive, so stop=11
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Challenge 3: Float range array

Create a NumPy array from **0 to 5** with a step size of **0.2**.

In [19]:
# 0 to 5 in steps of 0.2 (stop is exclusive, so 5 itself is not included)
np.arange(0, 5, 0.2)

# If 5 should be included: np.linspace(0, 5, 26)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

### Challenge 4: Random array

Create a NumPy array with shape **(2, 3)** filled with random values between 0 and 1.

In [20]:
# Shape (2, 3), random floats between 0 and 1
np.random.rand(2, 3)

array([[0.75694267, 0.03110769, 0.92539634],
       [0.80721136, 0.30537018, 0.21048644]])

---

## Part 2: Manipulating Arrays

### Challenge 5: Array with mixed-type input

Create a NumPy array from the values `(1, 3, '4', 7, 12, '0')`. Force the data type to **integer** using the `dtype` parameter.

> Notice that the string values `'4'` and `'0'` are silently cast to integers. NumPy arrays are homogeneous: all elements must share the same type.

In [21]:
# Mixed input, forced to integer
arr = np.array((1, 3, "4", 7, 12, "0"), dtype=int)
arr

array([ 1,  3,  4,  7, 12,  0])

### Challenge 6: Inspect dtype and shape

Using the array you created in Challenge 5, check:
- The **data type** of the elements
- The **shape** of the array

In [22]:
# Data type and shape
print(arr.dtype)
print(arr.shape)

int64
(6,)


### Challenge 7: Update a value by index

Update the **4th element** (index 3) of the array from Challenge 5 to the value `30`.

In [23]:
# 4th element (index 3) -> 30
arr[3] = 30
arr

array([ 1,  3,  4, 30, 12,  0])

### Challenge 8: Reshape to a 2×3 matrix

Reshape the array from Challenge 7 into a **2-row, 3-column** matrix. Print the result.

In [24]:
# 2 rows, 3 columns
matrix = arr.reshape(2, 3)
print(matrix)

[[ 1  3  4]
 [30 12  0]]


### Challenge 9: Row-wise addition

Using the 2×3 matrix from Challenge 8:
- Add **8** to every value in the **first row**
- Add **12** to every value in the **second row**

> Hint: index the rows and assign back in place.

In [25]:
# Add 8 to the first row, 12 to the second row (in place)
matrix[0] += 8
matrix[1] += 12
matrix

array([[ 9, 11, 12],
       [42, 24, 12]])

### Challenge 10: Column-wise multiplication

Multiply the columns of your matrix:
- **First column** × 2
- **Second column** × 3
- **Third column** × 4

> Hint: you can do this in one line using broadcasting with a 1D array `[2, 3, 4]`.

In [26]:
# Broadcasting: [2, 3, 4] is applied to every row, column by column
matrix = matrix * np.array([2, 3, 4])
matrix

array([[18, 33, 48],
       [84, 72, 48]])

### Challenge 11: Row sums

Calculate the **sum of all values in each row** of your matrix. You should get two totals, one per row.

In [27]:
# Sum of each row (axis=1 = across the columns)
matrix.sum(axis=1)

array([ 99, 204])

### Challenge 12: Column maximums

Find the **largest value in each column** of your matrix. You should get three values, one per column.

In [28]:
# Largest value in each column (axis=0 = down the rows)
matrix.max(axis=0)

array([84, 72, 48])

### Challenge 13: Index a single element

Extract the value from the **second column, first row** of your matrix.

> Reminder: NumPy uses `array[row, column]` indexing.

In [29]:
# First row (index 0), second column (index 1)
matrix[0, 1]

np.int64(33)

### Challenge 14: Find the index of a specific value

Find the **index** of the value `48` in your matrix.

> Hint: use `np.where()`. Note that depending on how your array evolved across previous challenges, your value at a given position may differ, first check what values are currently in the matrix.

In [30]:
# Current matrix, then the position(s) of 48
print(matrix)
rows, cols = np.where(matrix == 48)
print(list(zip(rows.tolist(), cols.tolist())))  # (row, column) pairs

[[18 33 48]
 [84 72 48]]
[(0, 2), (1, 2)]
